version: '2'
services:
  ticker-writer:
    build: .
    environment:
      - SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL
      - DB_HOST=influxdb
      - DB_PORT=8086
      - DB_NAME=ticker
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_RETENTION_DURATION=$DB_RETENTION_DURATION
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.3
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    ports:
      - '8083:8083'
      - '8086:8086'
