version: '2'
services:
  ticker-writer:
    build: .
    environment:
      - SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL
      - DB_HOST=influxdb
      - DB_PORT=8086
    depends_on:
      - influxdb

  influxdb:
    image: tutum/influxdb
    ports:
      - '8083:8083'
      - '8086:8086'
